/* Raw layer: faithful, all-text copies of the source CSVs.
Data was bulk-loaded via the DBeaver CSV import wizard (every column VARCHAR, no type coercion)
to tolerate blank/missing values in historical records.
Source CSVs were produced by the Python scrapers + combiner to get one integral file for each API
(e.g. bios_all.csv or players_box_scores_all.csv).
Type casting and cleaning happen later in 03_staging.sql. */


-- Player bios:

CREATE TABLE IF NOT EXISTS raw.bios (
	"PERSON_ID" VARCHAR,
	"FIRST_NAME" VARCHAR,
	"LAST_NAME" VARCHAR,
	"DISPLAY_FIRST_LAST" VARCHAR,
	"DISPLAY_LAST_COMMA_FIRST" VARCHAR,
	"DISPLAY_FI_LAST" VARCHAR,
	"PLAYER_SLUG" VARCHAR,
	"BIRTHDATE" VARCHAR,
	"SCHOOL" VARCHAR,
	"COUNTRY" VARCHAR,
	"LAST_AFFILIATION" VARCHAR,
	"HEIGHT" VARCHAR,
	"WEIGHT" VARCHAR,
	"SEASON_EXP" VARCHAR,
	"JERSEY" VARCHAR,
	"POSITION" VARCHAR,
	"ROSTERSTATUS" VARCHAR,
	"GAMES_PLAYED_CURRENT_SEASON_FLAG" VARCHAR,
	"TEAM_ID" VARCHAR,
	"TEAM_NAME" VARCHAR,
	"TEAM_ABBREVIATION" VARCHAR,
	"TEAM_CODE" VARCHAR,
	"TEAM_CITY" VARCHAR,
	"PLAYERCODE" VARCHAR,
	"FROM_YEAR" VARCHAR,
	"TO_YEAR" VARCHAR,
	"DLEAGUE_FLAG" VARCHAR,
	"NBA_FLAG" VARCHAR,
	"GAMES_PLAYED_FLAG" VARCHAR,
	"DRAFT_YEAR" VARCHAR,
	"DRAFT_ROUND" VARCHAR,
	"DRAFT_NUMBER" VARCHAR,
	"GREATEST_75_FLAG" VARCHAR,
	"PLAYER_ID" VARCHAR
);

-- Player boxscores:

CREATE TABLE IF NOT EXISTS raw.player_boxscores (
	"SEASON_ID" VARCHAR,
	"PLAYER_ID" VARCHAR,
	"PLAYER_NAME" VARCHAR,
	"TEAM_ID" VARCHAR,
	"TEAM_ABBREVIATION" VARCHAR,
	"TEAM_NAME" VARCHAR,
	"GAME_ID" VARCHAR,
	"GAME_DATE" VARCHAR,
	"MATCHUP" VARCHAR,
	"WL" VARCHAR,
	"MIN" VARCHAR,
	"FGM" VARCHAR,
	"FGA" VARCHAR,
	"FG_PCT" VARCHAR,
	"FG3M" VARCHAR,
	"FG3A" VARCHAR,
	"FG3_PCT" VARCHAR,
	"FTM" VARCHAR,
	"FTA" VARCHAR,
	"FT_PCT" VARCHAR,
	"OREB" VARCHAR,
	"DREB" VARCHAR,
	"REB" VARCHAR,
	"AST" VARCHAR,
	"STL" VARCHAR,
	"BLK" VARCHAR,
	"TOV" VARCHAR,
	"PF" VARCHAR,
	"PTS" VARCHAR,
	"PLUS_MINUS" VARCHAR,
	"FANTASY_PTS" VARCHAR,
	"VIDEO_AVAILABLE" VARCHAR,
	"Season" VARCHAR,
	"SeasonType" VARCHAR
);

-- Team boxscores:

CREATE TABLE IF NOT EXISTS raw.team_boxscores (
	"SEASON_ID" VARCHAR,
	"TEAM_ID" VARCHAR,
	"TEAM_ABBREVIATION" VARCHAR,
	"TEAM_NAME" VARCHAR,
	"GAME_ID" VARCHAR,
	"GAME_DATE" VARCHAR,
	"MATCHUP" VARCHAR,
	"WL" VARCHAR,
	"MIN" VARCHAR,
	"FGM" VARCHAR,
	"FGA" VARCHAR,
	"FG_PCT" VARCHAR,
	"FG3M" VARCHAR,
	"FG3A" VARCHAR,
	"FG3_PCT" VARCHAR,
	"FTM" VARCHAR,
	"FTA" VARCHAR,
	"FT_PCT" VARCHAR,
	"OREB" VARCHAR,
	"DREB" VARCHAR,
	"REB" VARCHAR,
	"AST" VARCHAR,
	"STL" VARCHAR,
	"BLK" VARCHAR,
	"TOV" VARCHAR,
	"PF" VARCHAR,
	"PTS" VARCHAR,
	"PLUS_MINUS" VARCHAR,
	"VIDEO_AVAILABLE" VARCHAR,
	"Season" VARCHAR,
	"SeasonType" VARCHAR
);