/* Model reference tables: manually-curated lookup tables with no dependencies
   on other objects. Created first so that the dimension builds can later join to them. */

-- country_codes - contain country name -> ISO-style 2-letter code, to help create country flag image URLs later when creating model.dim_players

CREATE TABLE IF NOT EXISTS model.country_codes (
    country VARCHAR,
    code VARCHAR
);

INSERT INTO model.country_codes (country, code)
VALUES
	('Angola','ao'),
	('Antigua and Barbuda','ag'),
	('Argentina','ar'),
	('Australia','au'),
	('Austria','at'),
	('Bahamas','bs'),
	('Belgium','be'),
	('Belize','bz'),
	('Bosnia and Herzegovina','ba'),
	('Brazil','br'),
	('British Virgin Islands','vg'),
	('Bulgaria','bg'),
	('Cabo Verde','cv'),
	('Cameroon','cm'),
	('Canada','ca'),
	('China','cn'),
	('Colombia','co'),
	('Congo','cg'),
	('Croatia','hr'),
	('Cuba','cu'),
	('Czech Republic','cz'),
	('Democratic Republic of the Congo','cd'),
	('Denmark','dk'),
	('Dominican Republic','do'),
	('Egypt','eg'),
	('Estonia','ee'),
	('Finland','fi'),
	('France','fr'),
	('Gabon','ga'),
	('Georgia','ge'),
	('Germany','de'),
	('Ghana','gh'),
	('Greece','gr'),
	('Guinea','gn'),
	('Haiti','ht'),
	('Iran','ir'),
	('Ireland','ie'),
	('Israel','il'),
	('Italy','it'),
	('Lebanon','lb'),
	('Jamaica','jm'),
	('Japan','jp'),
	('Latvia','lv'),
	('Lithuania','lt'),
	('North Macedonia','mk'),
	('Mali','ml'),
	('Mexico','mx'),
	('Montenegro','me'),
	('Netherlands','nl'),
	('New Zealand','nz'),
	('Nicaragua','ni'),
	('Nigeria','ng'),
	('Norway','no'),
	('Panama','pa'),
	('Poland','pl'),
	('Portugal','pt'),
	('Puerto Rico','pr'),
	('Romania','ro'),
	('Russia','ru'),
	('Saint Lucia','lc'),
	('Scotland','sc'),
	('Senegal','sn'),
	('Serbia','rs'),
	('Slovenia','si'),
	('South Korea','kr'),
	('South Sudan','ss'),
	('Spain','es'),
	('St. Vincent & Grenadines','vc'),
	('Sudan','sd'),
	('Sweden','se'),
	('Switzerland','ch'),
	('Tanzania','tz'),
	('Trinidad and Tobago','tt'),
	('Tunisia','tn'),
	('Turkey','tr'),
	('US Virgin Islands','vi'),
	('USA','us'),
	('Ukraine','ua'),
	('United Kingdom','gb'),
	('Uruguay','uy'),
	('Venezuela','ve'),
	('Uganda','ug');

-- team_logos_by_year - contain era-correct logo URL (data loaded separately via a manually curated CSV)

CREATE TABLE IF NOT EXISTS model.team_logos_by_year (
	team VARCHAR,
	year INT,
	logo VARCHAR
);


-- Reference table for disambiguating players with identical names.
-- Joined later into model.dim_players via COALESCE so only these specific player_ids get a custom name, while everyone else keeps their original NBA display name.

CREATE TABLE IF NOT EXISTS model.name_overrides (
    player_id BIGINT,
    name_override VARCHAR
);

INSERT INTO model.name_overrides (player_id, name_override)
VALUES
	(203318, 'Glen Rice Jr.'),
	(77178, 'Charles A. Jones'),
	(76531, 'Mike A. Davis'),
	(201607, 'Patrick Aloysius Ewing Jr.'),
	(78179, 'Charles E. Smith'),
	(1520, 'Charles C. Smith'),
	(77147, 'George E. Johnson'),
	(77149, 'George T. Johnson'),
	(203502, 'Tony LaShae Mitchell Jr.'),
	(203203, 'Chris T. Wright'),
	(203147, 'Jamahl Christopher Smith'),
	(1585, 'Brandon D. Williams'),
	(1628455, 'Mike P. James'),
	(78561, 'Nate Williams'),
	(203187, 'Christapher Johnson'),
	(77139, 'David Johnson (77139)'),
	(199, 'Reggie Silk Williams'),
	(78190, 'Greg D. Smith'),
	(77144, 'Eddie L. Johnson'),
	(201945, 'Gerald Henderson Jr.'),
	(78568, 'Samuel H. Williams'),
	(77202, 'Willie Jones'),
	(2399, 'Mike Dunleavy Jr.'),
	(76519, 'Charlie Davis'),
	(76518, 'Charles Davis'),
	(77268, 'George Smith King Jr.'),
	(78048, 'Walker Dwayne Russell Sr.'),
	(90000, 'Mark Anthony Jones'),
	(76528, 'Mark Giles Davis'),
	(1631098, 'Jonathan Davis'),
	(1538, 'Cedric Earl Henderson'),
	(78197, 'Michael John Smith'),
	(200784, 'Bobby Ray Jones'),
	(201173, 'Marcus Eliot Williams'),
	(200793, 'Daniel Brown'),
	(77154, 'Kenneth H. Johnson'),
	(77156, 'Larry O''Neal Johnson Sr.'),
	(77818, 'James Edward Paxson'),
	(120, 'Steve Smith'),
	(76609, 'Bob Duffy (76609)'),
	(76909, 'Matt Guokas (76909)'),
	(77203, 'Willie Jones (77203)'),
	(78209, 'Bill Smith (78209)'),
	(78382, 'Jack Turner (78382)'),
	(1631466, 'Jeenathan Williams');